# Generated by Django 5.1.7 on 2025-03-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_created_by_alter_coursereview_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='role',
            new_name='student_role',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='role',
            new_name='teacher_role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'client'), ('teacher', 'teacher'), ('administrator', 'administrator')], default='client', max_length=15),
        ),
    ]
