# Generated by Django 5.1.7 on 2025-04-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_role_student_student_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория'},
        ),
    ]
